name: Animal_Regist
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.13.0
  - torchvision>=0.14.0
  - torchaudio>=0.13.0
  - pytorch-cuda=11.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.1.0
  - scikit-image>=0.19.0
  - matplotlib>=3.5.0
  - pandas>=1.4.0
  - opencv>=4.6.0
  - blender  # For mesh deformation
  - pip
  - pip:
    - open3d>=0.16.0
    - trimesh>=3.15.0
    - mmengine>=0.8.0
    - mmcv>=2.0.1
    - mmdet>=3.1.0
    - mmpose>=1.1.0
    - xtcocotools>=1.12.0
    - pyyaml>=6.0
    - tqdm>=4.64.0
    - h5py>=3.7.0
    - Pillow>=9.2.0
    - pathlib2>=2.3.0
    - argparse-color-formatter>=1.2.2
    - colorama>=0.4.5